export const LOAD_COURSES = "LOAD_COURSES";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_COURSES_FAIL = "LOAD_COURSES_FAIL";

export const LOAD_AUTHOR = "LOAD_AUTHOR";
export const LOAD_AUTHOR_SUCCESS = "LOAD_AUTHOR_SUCCESS";
export const LOAD_AUTHOR_FAIL = "LOAD_AUTHOR_FAIL";

export const SAVE_COURSE = "SAVE_COURSE";
export const SAVE_COURSE_SUCCESS = "SAVE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const SAVE_COURSE_FAIL = "SAVE_COURSE_FAIL";
